title: David Lindell Farken 
subtitle: Sound Engineer 
description: Website and portfolio of David Lindell Farken, Sound Engineer, Light Technician, Stagecrafter.

author: David Lindell Farken 
email: davidlindellfarken@lfproductions.se
avatar: assets/images/avatar.jpg

baseurl: ""
url: "https://v3yiron.github.io"

 #Social settings
facebook_url: https://www.facebook.com/davidlindellfarken
github_url: https://github.com/v3yiron
linkedin_url: https://www.linkedin.com/in/david-lindell-farken-1274313b/
#twitter_url: https://twitter.com/chrisbobbe

# SEO settings
google_analytics: UA-112211352-1

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]
